// src/modules/goals/enums/goals.enum.ts

export enum GoalType {
  JOB_SEARCH = 'JOB_SEARCH',
  CAREER_GROWTH = 'CAREER_GROWTH',
  LEARNING = 'LEARNING',
  FITNESS = 'FITNESS',
  FINANCE = 'FINANCE',
  BUSINESS = 'BUSINESS',
  PERSONAL = 'PERSONAL',
  CUSTOM = 'CUSTOM',
}

export enum GoalStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RecruiterStatus {
  NOT_CONTACTED = 'NOT_CONTACTED',
  EMAIL_SENT = 'EMAIL_SENT',
  FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
  REPLIED = 'REPLIED',
  INTERVIEW = 'INTERVIEW',
  REJECTED = 'REJECTED',
  OFFER = 'OFFER',
}

export enum ActivityType {
  GOAL_CREATED = 'GOAL_CREATED',
  AI_PLAN_GENERATED = 'AI_PLAN_GENERATED',
  GOAL_UPDATED = 'GOAL_UPDATED',
  GOAL_STATUS_UPDATED = 'GOAL_STATUS_UPDATED',
  GOAL_PROGRESS_UPDATED = 'GOAL_PROGRESS_UPDATED',

  PLAN_ITEM_COMPLETED = 'PLAN_ITEM_COMPLETED',
  PLAN_ITEM_UNCOMPLETED = 'PLAN_ITEM_UNCOMPLETED',

  MILESTONE_COMPLETED = 'MILESTONE_COMPLETED',
  MILESTONE_UNCOMPLETED = 'MILESTONE_UNCOMPLETED',

  RECRUITER_ADDED = 'RECRUITER_ADDED',
  RECRUITER_UPDATED = 'RECRUITER_UPDATED',

  EMAIL_SENT_DETECTED = 'EMAIL_SENT_DETECTED',
  REPLY_DETECTED = 'REPLY_DETECTED',
  INTERVIEW_DETECTED = 'INTERVIEW_DETECTED',
  REJECTION_DETECTED = 'REJECTION_DETECTED',
  OFFER_DETECTED = 'OFFER_DETECTED',

  FOLLOW_UP_TASK_CREATED = 'FOLLOW_UP_TASK_CREATED',
}