// src/modules/goals/enums/goals.enum.ts

export enum GoalCategory {
  CAREER = 'CAREER',
  FITNESS = 'FITNESS',
  STUDY = 'STUDY',
  FINANCE = 'FINANCE',
  BUSINESS = 'BUSINESS',
  CUSTOM = 'CUSTOM',
}

export enum GoalType {
  JOB_SEARCH = 'JOB_SEARCH',
  CAREER_GROWTH = 'CAREER_GROWTH',
  LEARNING = 'LEARNING',
  FITNESS = 'FITNESS',
  FINANCE = 'FINANCE',
  BUSINESS = 'BUSINESS',
  PERSONAL = 'PERSONAL',
  CUSTOM = 'CUSTOM',
}

export enum GoalTemplateKey {
  JOB_SEARCH = 'JOB_SEARCH',

  WEIGHT_LOSS = 'WEIGHT_LOSS',
  WEIGHT_GAIN = 'WEIGHT_GAIN',

  EXAM_PREPARATION = 'EXAM_PREPARATION',
  SKILL_DEVELOPMENT = 'SKILL_DEVELOPMENT',

  SAVE_MONEY = 'SAVE_MONEY',
  DEBT_REDUCTION = 'DEBT_REDUCTION',

  START_BUSINESS = 'START_BUSINESS',
  GROW_REVENUE = 'GROW_REVENUE',

  CUSTOM = 'CUSTOM',
}

export enum GoalPlanSource {
  TEMPLATE = 'TEMPLATE',
  AI_GENERATED = 'AI_GENERATED',
  MANUAL = 'MANUAL',
}

export enum GoalActionFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  ONCE = 'ONCE',
}

export enum GoalActionPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum GoalStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum RecruiterStatus {
  NOT_CONTACTED = 'NOT_CONTACTED',
  EMAIL_SENT = 'EMAIL_SENT',
  FOLLOW_UP_DUE = 'FOLLOW_UP_DUE',
  REPLIED = 'REPLIED',
  INTERVIEW = 'INTERVIEW',
  REJECTED = 'REJECTED',
  OFFER = 'OFFER',
  NO_RESPONSE = 'NO_RESPONSE',
}

export enum ApplicationStatus {
  OUTREACH_SENT = 'OUTREACH_SENT',

  APPLIED = 'APPLIED',
  REPLIED = 'REPLIED',
  INTERVIEW = 'INTERVIEW',
  OFFER = 'OFFER',
  REJECTED = 'REJECTED',
  NO_RESPONSE = 'NO_RESPONSE',

  BOUNCED = 'BOUNCED',
}
export enum GoalIntelligenceEventType {
  APPLICATION_DETECTED = 'APPLICATION_DETECTED',

  RECRUITER_REPLY_DETECTED = 'RECRUITER_REPLY_DETECTED',

  INTERVIEW_DETECTED = 'INTERVIEW_DETECTED',

  OFFER_DETECTED = 'OFFER_DETECTED',

  REJECTION_DETECTED = 'REJECTION_DETECTED',

  FOLLOW_UP_CREATED = 'FOLLOW_UP_CREATED',

  NO_RESPONSE_DETECTED = 'NO_RESPONSE_DETECTED',

  COLD_EMAIL_DETECTED = 'COLD_EMAIL_DETECTED',

  EMAIL_BOUNCED = 'EMAIL_BOUNCED',
}

export enum ActivityType {
  GOAL_CREATED = 'GOAL_CREATED',

  TEMPLATE_SELECTED = 'TEMPLATE_SELECTED',
  AI_PLAN_GENERATED = 'AI_PLAN_GENERATED',
  AI_PLAN_REGENERATED = 'AI_PLAN_REGENERATED',

  GOAL_UPDATED = 'GOAL_UPDATED',
  GOAL_STATUS_UPDATED = 'GOAL_STATUS_UPDATED',
  GOAL_PROGRESS_UPDATED = 'GOAL_PROGRESS_UPDATED',

  GOAL_TASKS_CREATED = 'GOAL_TASKS_CREATED',
  GOAL_TASK_COMPLETED = 'GOAL_TASK_COMPLETED',

  PLAN_ITEM_COMPLETED = 'PLAN_ITEM_COMPLETED',
  PLAN_ITEM_UNCOMPLETED = 'PLAN_ITEM_UNCOMPLETED',

  MILESTONE_COMPLETED = 'MILESTONE_COMPLETED',
  MILESTONE_UNCOMPLETED = 'MILESTONE_UNCOMPLETED',

  RECRUITER_ADDED = 'RECRUITER_ADDED',
  RECRUITER_UPDATED = 'RECRUITER_UPDATED',

  APPLICATION_DETECTED = 'APPLICATION_DETECTED',

  EMAIL_SENT_DETECTED = 'EMAIL_SENT_DETECTED',
  COLD_EMAIL_DETECTED = 'COLD_EMAIL_DETECTED',

  EMAIL_BOUNCED = 'EMAIL_BOUNCED',

  REPLY_DETECTED = 'REPLY_DETECTED',
  INTERVIEW_DETECTED = 'INTERVIEW_DETECTED',
  REJECTION_DETECTED = 'REJECTION_DETECTED',
  OFFER_DETECTED = 'OFFER_DETECTED',

  FOLLOW_UP_TASK_CREATED = 'FOLLOW_UP_TASK_CREATED',

  NO_RESPONSE_DETECTED = 'NO_RESPONSE_DETECTED',
}

